import { existsSync, mkdirSync, readdirSync, readFileSync, unlinkSync } from "node:fs";
import { basename, join } from "node:path";
import chalk from "chalk";
import { sync as writeFileSync } from "write-file-atomic";
import { filterReadsFromAgents } from "../core/agents.js";
import type { Context } from "../core/context.js";
import { createContext } from "../core/context.js";
import type { Logger } from "../core/logger.js";
import { logSkipped } from "../core/logger.js";
import type { Manifest } from "../manifest.js";
import { contentHash, loadManifest, removeFromManifest, saveManifest, writeIfChanged } from "../manifest.js";
import { COMMANDS_DIR } from "../paths.js";
import { loadState } from "../state.js";
import type { CommandTransform, SyncOptions } from "../types.js";
import { AGENT_DEFINITIONS } from "../types.js";
import { ICON_SUCCESS } from "../ui/output.js";
import { expandHome } from "../utils.js";
import { delegateCommandsGenerate } from "./commands-delegate.js";
import { migrateLegacyShellPermissionMarkdown } from "./permission-patterns.js";

/**
 * Slices 2–5 of `delegate-commands-to-ai-rules` (TASKS.md): the agents
 * whose command content is generated by `ai-rules generate` instead of
 * via agentbrew's native transforms.
 *
 * Slice 2 (PR #889) shipped delegation for `claude-code` only.
 * Slice 3 (PR #890) added `cursor` — the CANARY_DELEGATED_AGENTS commands intersection.
 * Slice 4 (PR #891) hardened the contract: canary agents missing from
 * the delegation map SKIP — no source fallback. Cursor still applies
 * its native transform after delegation.
 * Slice 5 (this PR) adds `amp` + `firebender` as free-capability gains.
 * They had no `commandsDir` before; ai-rules covers them upstream so
 * adding the user-level paths to agents.yaml + this Set unlocks
 * delegated commands sync at zero native-code cost. The new agents
 * use ai-rules' `-ai-rules` suffix shape (handled by
 * `mapAiRulesNameToSource` in `commands-delegate.ts`).
 *
 * Carve-outs in `AGENTBREW_ONLY_COMMANDS_AGENTS` (gemini-cli, claude-desktop, opencode)
 * are filtered out by {@link buildAiRulesCommandsAgentList} — they
 * continue to use the native source-read + transform path. Their
 * rationale is documented in `AGENTBREW_ONLY_COMMANDS_RATIONALE`
 * (`src/core/commands-agent-map.ts`). Exported so {@link computeCommandsDiff}
 * can apply the slice 4 skip semantics.
 */
export const CANARY_DELEGATED_AGENTS: ReadonlySet<string> = new Set(["claude-code", "cursor", "amp", "firebender"]);

interface CommandTarget {
  agentName: string;
  dir: string;
  transform: CommandTransform;
  fileExt: string;
}

// ── Pure types ──────────────────────────────────────────────────────────────

interface CommandFileAction {
  filename: string;
  type: "write" | "prune";
  content?: string;
}

interface CommandTargetDiff {
  agentName: string;
  skipped: boolean;
  actions: CommandFileAction[];
  synced: number;
  pruned: number;
}

// ── Pure functions (no I/O, trivially testable) ─────────────────────────────

/** Remap a source .md filename to the target file extension. */
export function remapFilename(sourceFilename: string, targetExt: string): string {
  if (targetExt === ".md") return sourceFilename;
  return sourceFilename.replace(/\.md$/, targetExt);
}

/**
 * Compute per-target diff: what files to write/prune given source commands and existing target state.
 *
 * Slice 2 of `delegate-commands-to-ai-rules` introduced an optional
 * `delegated` map — agentbrew-canonical agent name → `Map<source filename,
 * ai-rules-generated content>`. Slice 4 hardened the contract: for
 * canary agents in {@link CANARY_DELEGATED_AGENTS}, the ONLY acceptable
 * source is `delegated`. When a canary agent doesn't appear in the
 * delegation map at all, the diff reports `skipped` — no fallback to
 * source. Carve-outs (not in `CANARY_DELEGATED_AGENTS`) continue to use
 * the source-content + transform path. Mirrors the rules-sync slice 4
 * evolution.
 */
export function computeCommandsDiff(
  sourceFiles: Array<{ filename: string; content: string }>,
  targets: Array<{
    agentName: string;
    exists: boolean;
    transform: CommandTransform;
    fileExt: string;
    existingFiles: Map<string, string>;
  }>,
  options?: { prune?: boolean },
  delegated?: ReadonlyMap<string, ReadonlyMap<string, string>>,
): CommandTargetDiff[] {
  const prune = options?.prune ?? false;
  return targets.map((target) => {
    const isCanary = CANARY_DELEGATED_AGENTS.has(target.agentName);
    const delegatedForAgent = delegated?.get(target.agentName);
    return computeSingleTargetDiff(target, sourceFiles, prune, delegatedForAgent, isCanary);
  });
}

interface TargetInput {
  agentName: string;
  exists: boolean;
  transform: CommandTransform;
  fileExt: string;
  existingFiles: Map<string, string>;
}

function computeSingleTargetDiff(
  target: TargetInput,
  sourceFiles: Array<{ filename: string; content: string }>,
  prune: boolean,
  delegatedForAgent: ReadonlyMap<string, string> | undefined,
  isCanary: boolean,
): CommandTargetDiff {
  if (!target.exists) {
    return { agentName: target.agentName, skipped: true, actions: [], synced: 0, pruned: 0 };
  }

  // Slice 4: canary agents (claude-code, cursor) MUST get content from
  // the delegation map. When the map has no entry for a canary agent,
  // the agent skips — no source fallback. Users without `ai-rules`
  // installed will see canary commands skip, mirroring the rules-sync
  // slice 4 hardening.
  if (isCanary && delegatedForAgent === undefined) {
    return { agentName: target.agentName, skipped: true, actions: [], synced: 0, pruned: 0 };
  }

  const actions: CommandFileAction[] = [];
  const targetFilenames = new Set<string>();

  for (const source of sourceFiles) {
    const targetFilename = remapFilename(source.filename, target.fileExt);
    targetFilenames.add(targetFilename);
    // Slices 2–4: prefer ai-rules-generated content as the source for
    // delegated agents, then apply the agent's native transform on
    // top. For claude-code (identity) the transform is a no-op so the
    // delegated content survives byte-for-byte. For cursor, delegated
    // ai-rules output is converted to Cursor's command format.
    // Carve-outs (not in CANARY_DELEGATED_AGENTS) read source content + apply transform.
    const baseContent = delegatedForAgent?.get(source.filename) ?? source.content;
    const transformed = target.transform(baseContent);
    const existing = target.existingFiles.get(targetFilename);
    if (existing !== transformed) {
      actions.push({ filename: targetFilename, type: "write", content: transformed });
    }
  }

  let pruneCount = 0;
  if (prune) {
    for (const [filename] of target.existingFiles) {
      if (!targetFilenames.has(filename)) {
        actions.push({ filename, type: "prune" });
        pruneCount++;
      }
    }
  }

  const synced = actions.filter((a) => a.type === "write").length;
  return { agentName: target.agentName, skipped: false, actions, synced, pruned: pruneCount };
}

const identity: CommandTransform = (content) => content;

export function getCommandTargets(): CommandTarget[] {
  const withCommands = AGENT_DEFINITIONS.filter((a) => a.commandsDir !== undefined);
  const detectedNames = new Set(withCommands.map((a) => a.name));
  const filtered = filterReadsFromAgents(withCommands, detectedNames);
  return filtered.map((a) => ({
    agentName: a.name,
    dir: a.commandsDir ?? "",
    transform: a.commandTransform ?? identity,
    fileExt: a.commandFileExt ?? ".md",
  }));
}

/** Returns the canonical path for agentbrew user commands — used by portable.ts to avoid duplicate path strings. */
export function getCommandsDir(): string {
  return expandHome(COMMANDS_DIR);
}

/** Check if a file was modified by the user since agentbrew last deployed it.
 *  Returns true if the file exists but isn't tracked in the manifest (user-created)
 *  or if its content doesn't match what agentbrew last wrote. */
function isUserModified(filePath: string, manifest: Manifest): boolean {
  if (!existsSync(filePath)) return false;
  const lastDeployedHash = manifest.hashes[filePath];
  if (!lastDeployedHash) return true; // File exists but not tracked — user-created, don't overwrite
  try {
    const currentContent = readFileSync(filePath, "utf-8");
    return contentHash(currentContent) !== lastDeployedHash;
  } catch (e) {
    logSkipped("sync/command-sync/contentHash", e);
    return false;
  }
}

interface ExtendedTargetInput {
  agentName: string;
  targetDir: string;
  exists: boolean;
  transform: CommandTransform;
  fileExt: string;
  existingFiles: Map<string, string>;
}

function resolveCmdSyncOptions(options?: SyncOptions): {
  quiet: boolean;
  verbose: boolean;
  dryRun: boolean;
  prune: boolean;
} {
  return {
    quiet: options?.quiet ?? false,
    verbose: options?.verbose ?? false,
    dryRun: options?.dryRun ?? false,
    prune: options?.prune ?? false,
  };
}

function readSourceCommands(
  commandsDir: string,
  quiet: boolean,
  log: Logger,
): Array<{ filename: string; content: string }> {
  const files = readdirSync(commandsDir).filter((f) => f.endsWith(".md"));
  const sourceFiles: Array<{ filename: string; content: string }> = [];
  for (const filename of files) {
    try {
      sourceFiles.push({ filename, content: readFileSync(join(commandsDir, filename), "utf-8") });
    } catch (e) {
      logSkipped("sync/command-sync/push", e);
      if (!quiet) log.error(`  ✗ command-sync: ${filename} — unreadable, skipping`);
    }
  }
  return sourceFiles;
}

function readExistingTargetFiles(targetDir: string, ext: string): Map<string, string> {
  const existingFiles = new Map<string, string>();
  try {
    for (const file of readdirSync(targetDir).filter((f) => f.endsWith(ext))) {
      try {
        existingFiles.set(file, readFileSync(join(targetDir, file), "utf-8"));
      } catch (e) {
        logSkipped("sync/command-sync/set", e);
        // skip unreadable file
      }
    }
  } catch (e) {
    logSkipped("sync/command-sync/readExistingTargetFiles/readdir", e);
    // dir not readable
  }
  return existingFiles;
}

function buildTargetInputs(targets: CommandTarget[]): ExtendedTargetInput[] {
  return targets.map((target) => {
    const targetDir = expandHome(target.dir);
    const exists = existsSync(targetDir);
    const existingFiles = exists ? readExistingTargetFiles(targetDir, target.fileExt) : new Map<string, string>();
    return {
      agentName: target.agentName,
      targetDir,
      exists,
      transform: target.transform,
      fileExt: target.fileExt,
      existingFiles,
    };
  });
}

/**
 * Delete a previously deployed command file. Returns `true` only when
 * the file was actually removed; `false` for files agentbrew never
 * tracked (user-created — left in place).
 *
 * Returning the actual outcome lets the caller report a truthful
 * "N pruned" count. Before this change, `computeSingleTargetDiff`
 * emitted a prune action for every existing target file not in
 * source — including user-created ones — and the summary counted them
 * as pruned even though `applyPruneAction` silently skipped them. On
 * a real laptop with many user-created commands in `~/.claude/commands/`
 * and more in `~/.cursor/commands/`, every sync printed inflated `N pruned` while
 * actually deleting nothing. Filed as the
 * `command-sync-prune-count-honest` scout in TASKS.md.
 */
function applyPruneAction(filePath: string, manifest: Manifest): boolean {
  if (!manifest.hashes[filePath]) return false;
  unlinkSync(filePath);
  removeFromManifest(filePath, manifest);
  return true;
}

interface WriteActionOpts {
  filePath: string;
  action: CommandFileAction;
  agentName: string;
  manifest: Manifest;
  quiet: boolean;
  log: Logger;
}

/** Write merged command sources into the canonical commands dir so lint/status see overrides. */
function refreshCanonicalCommandSources(
  sourceFiles: ReadonlyArray<{ filename: string; content: string }>,
  opts: { dryRun: boolean; manifest: Manifest },
): void {
  const canonicalDir = getCommandsDir();
  mkdirSync(canonicalDir, { recursive: true });
  for (const { filename, content } of sourceFiles) {
    if (opts.dryRun) continue;
    writeIfChanged(join(canonicalDir, filename), content, opts.manifest);
  }
}

function handleWriteAction(opts: WriteActionOpts): boolean {
  const { filePath, action, agentName, manifest, quiet, log } = opts;
  // Skip user-modified files — the user's edits take priority, except in-place
  // Exec/Shell → Bash permission migration when that is the only needed change.
  if (isUserModified(filePath, manifest)) {
    try {
      const currentContent = readFileSync(filePath, "utf-8");
      const migratedContent = migrateLegacyShellPermissionMarkdown(currentContent);
      if (migratedContent !== currentContent) {
        writeIfChanged(filePath, migratedContent, manifest);
        if (!quiet) {
          log.log(`  ↻ ${agentName}: migrated permission patterns in user-modified ${action.filename}`);
        }
        return false;
      }
    } catch (e) {
      logSkipped("sync/command-sync/inPlacePermissionMigration", e);
    }
    if (!quiet) {
      log.log(`  ⚠ ${agentName}: skipping ${action.filename} (user-modified)`);
    }
    return true;
  }
  const content = action.content ?? "";
  writeIfChanged(filePath, content, manifest);
  return false;
}

interface ApplyActionOpts {
  action: CommandFileAction;
  targetDir: string;
  agentName: string;
  manifest: Manifest;
  quiet: boolean;
  log: Logger;
}

/**
 * Apply a single diff action and report its outcome.
 *
 * Returns a discriminated result so callers can count writes-skipped
 * (user-modified files) and actual prunes (deleted manifest-tracked
 * files) separately. The "would-prune" count from
 * {@link computeSingleTargetDiff} includes user-created files agentbrew
 * never tracked — only counting actual deletions keeps the
 * `agentbrew sync` summary truthful.
 */
function applySingleAction(opts: ApplyActionOpts): { writeSkipped: boolean; prunedFile: boolean } {
  const { action, targetDir, agentName, manifest, quiet, log } = opts;
  const filePath = join(targetDir, action.filename);
  if (action.type === "write") {
    const skipped = handleWriteAction({ filePath, action, agentName, manifest, quiet, log });
    return { writeSkipped: skipped, prunedFile: false };
  }
  // Only prune files that agentbrew deployed (tracked in manifest).
  // applyPruneAction returns false for user-created files — those
  // survive and don't count toward the "N pruned" summary.
  return { writeSkipped: false, prunedFile: applyPruneAction(filePath, manifest) };
}

function applyDiffActions(
  diff: CommandTargetDiff,
  targetDir: string,
  manifest: Manifest,
  quiet: boolean,
  log: Logger,
): { skipped: number; actualPruned: number } {
  let skipped = 0;
  let actualPruned = 0;
  for (const action of diff.actions) {
    try {
      const result = applySingleAction({ action, targetDir, agentName: diff.agentName, manifest, quiet, log });
      if (result.writeSkipped) skipped++;
      if (result.prunedFile) actualPruned++;
    } catch (e) {
      logSkipped("sync/command-sync/applySingleAction", e);
      // skip write/prune errors for individual files
    }
  }
  return { skipped, actualPruned };
}

interface LogCmdDiffOpts {
  diff: CommandTargetDiff;
  agentSkipped: number;
  actualPruned: number;
  dryRun: boolean;
  verbose: boolean;
  log: Logger;
}

function logCmdDiffResult(opts: LogCmdDiffOpts): void {
  const { diff, agentSkipped, actualPruned, dryRun, verbose, log } = opts;
  const changes: string[] = [];
  if (diff.synced > 0) changes.push(`${diff.synced - agentSkipped} updated`);
  if (agentSkipped > 0) changes.push(`${agentSkipped} user-modified`);
  // Use the actual number of files removed, not the diff's
  // "would-prune" count which includes user-created files we
  // intentionally leave alone. Dry-run reports the diff count
  // because no files are actually deleted yet — the user wants to
  // see what WOULD happen.
  const reportedPruned = dryRun ? diff.pruned : actualPruned;
  if (reportedPruned > 0) changes.push(log.red(`${reportedPruned} pruned`));
  if (!verbose && changes.length === 0) return;
  const summary = changes.length > 0 ? changes.join(", ") : "up to date";
  const icon = dryRun ? log.blue("~") : log.green("✓");
  log.log(`  ${icon} ${diff.agentName} — ${summary}`);
}

function logCmdSyncSummary(
  totals: { synced: number; pruned: number; skipped: number; missingDir: number },
  dryRun: boolean,
  log: Logger,
): void {
  const parts = [`${totals.synced} written`];
  if (totals.skipped > 0) parts.push(`${totals.skipped} user-modified (skipped)`);
  if (totals.pruned > 0) parts.push(`${totals.pruned} pruned`);
  log.log(`${log.bold(dryRun ? "\nWould apply:" : "\nDone.")} ${parts.join(", ")}.\n`);
  if (totals.missingDir > 0) {
    const noun = totals.missingDir === 1 ? "agent has" : "agents have";
    log.log(
      log.dim(
        `  ℹ ${totals.missingDir} ${noun} no commands dir yet — open each once to create it (run with --verbose to list).`,
      ),
    );
  }
}

function warnNoCommandsDir(quiet: boolean, log: Logger): void {
  if (quiet) return;
  log.warn("No commands directory found.");
  log.log(`Create commands in: ${getCommandsDir()}`);
  log.log("Or run `agentbrew commands init` to set up.");
}

function warnNoCommands(quiet: boolean, log: Logger): void {
  if (quiet) return;
  log.warn("No commands found.");
  log.log(`Add .md files to: ${getCommandsDir()}`);
}

function getAllCommandSourceDirs(): string[] {
  const sourceDirs: string[] = [];
  const seen = new Set<string>();

  const addDir = (dir: string): void => {
    if (seen.has(dir) || !existsSync(dir)) return;
    seen.add(dir);
    sourceDirs.push(dir);
  };

  addDir(getCommandsDir());

  const state = loadState();
  for (const dir of state?.commandSourceDirs ?? []) {
    addDir(expandHome(dir.path));
  }

  return sourceDirs;
}

function resolveLogger(ctx: Partial<Context> | undefined, quiet: boolean, compact?: boolean): Logger {
  if (ctx?.logger) return ctx.logger;
  return createContext({ quiet, compact }).logger;
}

function resolveManifest(ctx: Partial<Context> | undefined): Manifest {
  if (ctx?.manifest !== undefined) return ctx.manifest;
  return loadManifest();
}

function getSyncLabel(dryRun: boolean, count: number): string {
  if (dryRun) return "Dry run — commands";
  return `Syncing ${count} commands...`;
}

interface ProcessDiffOpts {
  diff: CommandTargetDiff;
  targetDir: string;
  manifest: Manifest;
  dryRun: boolean;
  quiet: boolean;
  verbose: boolean;
  log: Logger;
}

function processSingleDiff(opts: ProcessDiffOpts): {
  synced: number;
  pruned: number;
  skipped: number;
  missingDir: number;
} {
  const { diff, targetDir, manifest, dryRun, quiet, verbose, log } = opts;
  if (diff.skipped) {
    // Per-agent "dir not found" lines are spammy noise in the common case
    // (many agents detected, most without a commands/ dir yet).
    // Verbose mode keeps the detail for debugging; non-verbose shows a
    // single collapsed "N agents have no commands dir yet" summary line.
    if (!quiet && verbose) log.log(log.dim(`  - ${diff.agentName} — skipped (dir not found)`));
    return { synced: 0, pruned: 0, skipped: 0, missingDir: 1 };
  }
  if (dryRun) {
    // Dry-run reports the would-prune count from the diff because
    // no files are actually deleted; the user wants the preview.
    return { synced: diff.synced, pruned: diff.pruned, skipped: 0, missingDir: 0 };
  }
  const { skipped: agentSkipped, actualPruned } = applyDiffActions(diff, targetDir, manifest, quiet, log);
  // Use the actual number deleted, not the diff's would-prune
  // count. The diff includes user-created files agentbrew never
  // tracked; `applyPruneAction` correctly leaves those in place but
  // before this fix they still inflated the summary. See the
  // `command-sync-prune-count-honest` scout in TASKS.md.
  return { synced: diff.synced - agentSkipped, pruned: actualPruned, skipped: agentSkipped, missingDir: 0 };
}

/** Collect command source files from the global dir and any Agentfile-declared dirs. */
function describeSourceDir(commandsDir: string): string {
  return commandsDir === getCommandsDir() ? "global commands" : commandsDir;
}

function collectAllSourceCommands(
  sourceDirs: string[],
  quiet: boolean,
  verbose: boolean,
  log: Logger,
): Array<{ filename: string; content: string }> {
  const sourceFiles = new Map<string, { content: string; filename: string; sourceDir: string }>();

  for (const sourceDir of sourceDirs) {
    const extra = readSourceCommands(sourceDir, quiet, log);
    for (const file of extra) {
      const existing = sourceFiles.get(file.filename);
      if (existing && !quiet && verbose) {
        log.log(
          log.dim(
            `Duplicate command source for ${file.filename}: ${describeSourceDir(sourceDir)} overrides ${describeSourceDir(existing.sourceDir)}.`,
          ),
        );
      }
      sourceFiles.set(file.filename, { ...file, sourceDir });
    }
  }

  return [...sourceFiles.values()].map(({ filename, content }) => ({ filename, content }));
}

/**
 * Slice 2 of `delegate-commands-to-ai-rules`: invoke
 * {@link delegateCommandsGenerate} for the canary agents only. Returns
 * an empty Map (so every target falls through to the native transform)
 * when:
 *   - no canary appears in the targets list,
 *   - `sourceFiles` is empty (nothing to delegate; native path also no-ops),
 *   - or the helper returned empty (binary missing / subprocess failure /
 *     unreadable output — see {@link delegateCommandsGenerate} contract).
 *
 * Exported so tests + future drift-checks can compute the SAME per-target
 * content `syncCommands` writes without re-deriving the canary list.
 */
export function collectCanaryDelegation(
  targets: ReadonlyArray<{ agentName: string }>,
  sourceFiles: ReadonlyArray<{ filename: string; content: string }>,
): ReadonlyMap<string, ReadonlyMap<string, string>> {
  if (sourceFiles.length === 0) return new Map();
  const canaryAgents = targets.map((t) => t.agentName).filter((name) => CANARY_DELEGATED_AGENTS.has(name));
  if (canaryAgents.length === 0) return new Map();
  return delegateCommandsGenerate({ agents: canaryAgents, sourceCommands: sourceFiles });
}

export async function syncCommands(options?: SyncOptions, ctx?: Partial<Context>): Promise<void> {
  const { quiet, verbose, dryRun, prune } = resolveCmdSyncOptions(options);
  const log = resolveLogger(ctx, quiet, options?.compact);

  // ── Read phase ──────────────────────────────────────────────────────────
  const sourceDirs = getAllCommandSourceDirs();
  if (sourceDirs.length === 0) {
    warnNoCommandsDir(quiet, log);
    return;
  }

  const sourceFiles = collectAllSourceCommands(sourceDirs, quiet, verbose, log);

  if (sourceFiles.length === 0 && !prune) {
    warnNoCommands(quiet, log);
    return;
  }

  const targetInputs = buildTargetInputs(getCommandTargets());

  // Slice 2 of `delegate-commands-to-ai-rules`: invoke ai-rules for the
  // canary agents only. Returns an empty Map when no canary appears in
  // the targets list, the binary is missing, or the subprocess fails —
  // every target then falls through to the native transform path.
  const delegated = collectCanaryDelegation(targetInputs, sourceFiles);

  // ── Pure diff phase ─────────────────────────────────────────────────────
  const diffs = computeCommandsDiff(sourceFiles, targetInputs, { prune }, delegated);

  // ── Apply phase ─────────────────────────────────────────────────────────
  const label = getSyncLabel(dryRun, sourceFiles.length);
  if (!quiet) log.log(log.bold(`\n${label}\n`));

  const sharedManifest = ctx?.manifest !== undefined;
  const manifest = resolveManifest(ctx);
  refreshCanonicalCommandSources(sourceFiles, { dryRun, manifest });
  const totals = { synced: 0, pruned: 0, skipped: 0, missingDir: 0 };

  for (let i = 0; i < diffs.length; i++) {
    const result = processSingleDiff({
      diff: diffs[i],
      targetDir: targetInputs[i].targetDir,
      manifest,
      dryRun,
      quiet,
      verbose,
      log,
    });
    totals.synced += result.synced;
    totals.pruned += result.pruned;
    totals.skipped += result.skipped;
    totals.missingDir += result.missingDir;
    if (!quiet) {
      logCmdDiffResult({
        diff: diffs[i],
        agentSkipped: result.skipped,
        actualPruned: result.pruned,
        dryRun,
        verbose,
        log,
      });
    }
  }

  if (!dryRun && !sharedManifest) saveManifest(manifest);
  if (!quiet) logCmdSyncSummary(totals, dryRun, log);
}

export async function initCommands(): Promise<void> {
  const commandsDir = getCommandsDir();

  if (existsSync(commandsDir) && readdirSync(commandsDir).length > 0) {
    const count = readdirSync(commandsDir).filter((f) => f.endsWith(".md")).length;
    console.log(chalk.yellow(`Commands directory already exists with ${count} command(s).`));
    console.log(`  ${commandsDir}`);
    return;
  }

  mkdirSync(commandsDir, { recursive: true });

  // Create a starter command
  const starter = `---
description: Example command — replace with your own
---

# Hello World

This is an example agentbrew command. Edit or replace this file.

## Steps

<!-- turbo -->
\`\`\`bash
echo "Hello from agentbrew!"
\`\`\`
`;

  writeFileSync(join(commandsDir, "hello.md"), starter, "utf-8");
  console.log(`${ICON_SUCCESS} Commands directory created: ${commandsDir}`);
  console.log("  Starter command: hello.md");
  console.log("\n  Add .md files there, then run `agentbrew sync --only commands`.");
}

export async function listCommands(): Promise<void> {
  const sourceDirs = getAllCommandSourceDirs();
  if (sourceDirs.length === 0) {
    console.error(chalk.yellow("No commands directory found."));
    console.log("Run `agentbrew commands init` to set up.");
    return;
  }

  const log = createContext({ quiet: false }).logger;
  const files = collectAllSourceCommands(sourceDirs, false, true, log);

  console.log(chalk.bold(`\nCommands (${files.length})\n`));

  for (const file of files) {
    const { content, filename } = file;
    const descMatch = content.match(/^---\n[\s\S]*?description:\s*(.+)\n[\s\S]*?---/);
    const desc = descMatch?.[1] ?? "";
    const name = basename(filename, ".md");
    console.log(`  ${chalk.cyan(name)}${desc ? chalk.dim(` — ${desc}`) : ""}`);
  }

  if (sourceDirs.length === 1) {
    console.log(chalk.dim(`\n  Dir: ${sourceDirs[0]}`));
  } else {
    console.log(chalk.dim("\n  Dirs:"));
    for (const sourceDir of sourceDirs) {
      console.log(chalk.dim(`    ${sourceDir}`));
    }
  }

  // Show deployment status
  const targets = getCommandTargets();
  console.log(chalk.bold("\nDeployed to:\n"));
  for (const target of targets) {
    const dir = expandHome(target.dir);
    if (existsSync(dir)) {
      console.log(`  ${ICON_SUCCESS} ${target.agentName} (${target.dir})`);
    } else {
      console.log(chalk.dim(`  - ${target.agentName} (not found)`));
    }
  }
  console.log();
}

export async function addCommand(sourcePath: string): Promise<void> {
  const expanded = expandHome(sourcePath);
  if (!existsSync(expanded)) {
    console.error(chalk.red(`File not found: ${expanded}`));
    return;
  }

  const commandsDir = getCommandsDir();
  mkdirSync(commandsDir, { recursive: true });

  const fileName = basename(expanded);
  const target = join(commandsDir, fileName);
  const content = readFileSync(expanded, "utf-8");
  writeFileSync(target, content, "utf-8");

  console.log(`${ICON_SUCCESS} Command added: ${fileName}`);
  console.log("  Run `agentbrew sync --only commands` to deploy to all agents.");
}
