import { appendFileSync, existsSync, mkdirSync, readFileSync, unlinkSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import chalk from "chalk";
import type { Command } from "commander";
import { sync as writeFileAtomicSync } from "write-file-atomic";
import { errorMessage } from "./core/errors.js";
import { ICON_SUCCESS } from "./ui/output.js";

interface CommandInfo {
  name: string;
  description: string;
  options: Array<{ flags: string; description: string }>;
  subcommands: CommandInfo[];
}

function collectCommands(cmd: Command): CommandInfo[] {
  return cmd.commands.map((sub: Command) => ({
    name: sub.name(),
    description: sub.description(),
    options: sub.options.map((opt) => ({
      flags: opt.long ?? opt.short ?? "",
      description: opt.description,
    })),
    subcommands: collectCommands(sub),
  }));
}

function generateBashCompletion(commands: CommandInfo[]): string {
  const topLevelNames = commands.map((c) => c.name).join(" ");

  const subcaseClauses = commands
    .filter((c) => c.subcommands.length > 0)
    .map((c) => {
      const subNames = c.subcommands.map((s) => s.name).join(" ");
      return `        ${c.name})\n            COMPREPLY=($(compgen -W "${subNames}" -- "\${cur}"))\n            return 0\n            ;;`;
    })
    .join("\n");

  return `# agentbrew bash completion
# Generated by: agentbrew completions bash
_agentbrew_completions() {
    local cur prev words cword
    _init_completion || return

    local commands="${topLevelNames}"

    if [[ \${cword} -eq 1 ]]; then
        COMPREPLY=($(compgen -W "\${commands}" -- "\${cur}"))
        return 0
    fi

    case "\${words[1]}" in
${subcaseClauses}
        *)
            COMPREPLY=()
            ;;
    esac
}

complete -F _agentbrew_completions agentbrew
`;
}

function generateZshCompletion(commands: CommandInfo[]): string {
  const topLevel = commands.map((c) => `    '${c.name}:${escapeZsh(c.description)}'`).join(" \\\n");

  const subcommandFunctions = commands
    .filter((c) => c.subcommands.length > 0)
    .map((c) => {
      const subs = c.subcommands.map((s) => `        '${s.name}:${escapeZsh(s.description)}'`).join(" \\\n");

      return `_agentbrew_${c.name}() {
    local -a subcommands
    subcommands=(
${subs}
    )
    _describe 'subcommand' subcommands
}`;
    })
    .join("\n\n");

  const subcases = commands
    .filter((c) => c.subcommands.length > 0)
    .map((c) => `        ${c.name}) _agentbrew_${c.name} ;;`)
    .join("\n");

  return `#compdef agentbrew
# agentbrew zsh completion
# Generated by: agentbrew completions zsh

_agentbrew() {
    local -a commands
    commands=(
${topLevel}
    )

    _arguments -C \\
        '1:command:->command' \\
        '*::arg:->args'

    case $state in
        command)
            _describe 'command' commands
            ;;
        args)
            case $words[1] in
${subcases}
            esac
            ;;
    esac
}

${subcommandFunctions}

_agentbrew "$@"
`;
}

function generateFishCompletion(commands: CommandInfo[]): string {
  const lines: string[] = [
    "# agentbrew fish completion",
    "# Generated by: agentbrew completions fish",
    "",
    "# Disable file completions by default",
    "complete -c agentbrew -f",
    "",
  ];

  for (const cmd of commands) {
    lines.push(`complete -c agentbrew -n '__fish_use_subcommand' -a '${cmd.name}' -d '${escapeFish(cmd.description)}'`);
  }

  lines.push("");

  for (const cmd of commands) {
    for (const opt of cmd.options) {
      const long = opt.flags.replace(/^--/, "");
      if (long) {
        lines.push(
          `complete -c agentbrew -n '__fish_seen_subcommand_from ${cmd.name}' -l '${long}' -d '${escapeFish(opt.description)}'`,
        );
      }
    }

    for (const sub of cmd.subcommands) {
      lines.push(
        `complete -c agentbrew -n '__fish_seen_subcommand_from ${cmd.name}' -a '${sub.name}' -d '${escapeFish(sub.description)}'`,
      );
    }
  }

  lines.push("");
  return lines.join("\n");
}

function escapeZsh(text: string): string {
  return text.replace(/'/g, "'\\''").replace(/\[/g, "\\[").replace(/\]/g, "\\]");
}

function escapeFish(text: string): string {
  return text.replace(/'/g, "\\'");
}

type Shell = "bash" | "zsh" | "fish";

function detectShell(): Shell {
  const shellEnv = process.env.SHELL ?? "";
  if (shellEnv.includes("zsh")) return "zsh";
  if (shellEnv.includes("fish")) return "fish";
  return "bash";
}

export function generateCompletion(program: Command, shell?: string): string {
  const targetShell = (shell ?? detectShell()) as Shell;
  const commands = collectCommands(program);

  switch (targetShell) {
    case "bash":
      return generateBashCompletion(commands);
    case "zsh":
      return generateZshCompletion(commands);
    case "fish":
      return generateFishCompletion(commands);
    default:
      throw new Error(`Unsupported shell: ${targetShell}. Use bash, zsh, or fish.`);
  }
}

export function installCompletion(program: Command, shell?: string): void {
  const targetShell = (shell ?? detectShell()) as Shell;
  const script = generateCompletion(program, targetShell);
  const home = homedir();

  try {
    switch (targetShell) {
      case "bash": {
        const completionDir = join(home, ".local", "share", "bash-completion", "completions");
        mkdirSync(completionDir, { recursive: true });
        const completionFile = join(completionDir, "agentbrew");
        writeFileAtomicSync(completionFile, script);
        console.log(`${ICON_SUCCESS} Bash completion installed to ${completionFile}`);
        console.log(chalk.dim(`  Restart your shell or run: source ${completionFile}`));
        break;
      }

      case "zsh": {
        const completionDir = join(home, ".local", "share", "zsh", "site-functions");
        mkdirSync(completionDir, { recursive: true });
        const completionFile = join(completionDir, "_agentbrew");
        writeFileAtomicSync(completionFile, script);

        const zshrc = join(home, ".zshrc");
        const fpathLine = `fpath=(${completionDir} $fpath)`;
        if (existsSync(zshrc)) {
          const content = readFileSync(zshrc, "utf-8");
          if (!content.includes(completionDir)) {
            appendFileSync(zshrc, `\n# agentbrew completions\n${fpathLine}\nautoload -Uz compinit && compinit\n`);
            console.log(`${ICON_SUCCESS} Zsh completion installed to ${completionFile}`);
            console.log(chalk.dim("  Added fpath to ~/.zshrc. Restart your shell to activate."));
          } else {
            writeFileAtomicSync(completionFile, script);
            console.log(`${ICON_SUCCESS} Zsh completion updated at ${completionFile}`);
            console.log(chalk.dim("  Restart your shell or run: exec zsh"));
          }
        } else {
          writeFileAtomicSync(completionFile, script);
          console.log(`${ICON_SUCCESS} Zsh completion installed to ${completionFile}`);
          console.log(chalk.dim(`  Add to ~/.zshrc: ${fpathLine}`));
        }
        break;
      }

      case "fish": {
        const completionDir = join(home, ".config", "fish", "completions");
        mkdirSync(completionDir, { recursive: true });
        const completionFile = join(completionDir, "agentbrew.fish");
        writeFileAtomicSync(completionFile, script);
        console.log(`${ICON_SUCCESS} Fish completion installed to ${completionFile}`);
        console.log(chalk.dim("  Completions are active immediately in new fish sessions."));
        break;
      }
    }
  } catch (error) {
    const msg = errorMessage(error);
    console.error(chalk.red(`Failed to install ${targetShell} completion: ${msg}`));
    console.log(chalk.dim("  Check file permissions and try again, or run with sudo."));
    process.exitCode = 1;
  }
}

export function uninstallCompletion(shell?: string): void {
  const targetShell = (shell ?? detectShell()) as Shell;
  const home = homedir();

  const paths: Record<Shell, string> = {
    bash: join(home, ".local", "share", "bash-completion", "completions", "agentbrew"),
    zsh: join(home, ".local", "share", "zsh", "site-functions", "_agentbrew"),
    fish: join(home, ".config", "fish", "completions", "agentbrew.fish"),
  };

  const completionFile = paths[targetShell];
  try {
    if (existsSync(completionFile)) {
      unlinkSync(completionFile);
      console.log(`${ICON_SUCCESS} Removed ${targetShell} completion: ${completionFile}`);
    } else {
      console.log(chalk.dim(`No ${targetShell} completion found at ${completionFile}`));
    }
  } catch (error) {
    const msg = errorMessage(error);
    console.error(chalk.red(`Failed to remove ${targetShell} completion: ${msg}`));
    console.log(chalk.dim("  Check file permissions and try again, or run with sudo."));
    process.exitCode = 1;
  }
}
